### ISSUE TITLE
Understand Mixed dataset

### ISSUE THREAD

**Issue by MathildeDupouy** [balthazarneveu/gyraudio#16]
An understanding of the mixing rules on the given dataset would help determine loss and analyse results.
Especially, a time-frequency representation may help understand.

**Comment by MathildeDupouy** [comment]
- [ ] Conduct experiments to try reproducing mixed signals
- [ ] Enable visualization of the STFT of mixed and ground truth signals
- [ ] Compute masks on STFT
- [ ] Visualize masks

**Comment by balthazarneveu** [comment]
Note:
- What if the mix =  x+ alpha*noise  is considered as the noise in the SNR definition...
- What if the norm in the expected  SNR is not L² but like the max?
