### ISSUE TITLE
audiosep reloaded: restart on the additive mix

### ISSUE THREAD

**Issue by balthazarneveu** [balthazarneveu/gyraudio#18]
- [x] reset exeperiments
- [x] change wandb default
- [x] change output folder (default + kaggle notebook)

# Training
@MathildeDupouy 
- [x] dataloader  ....

@balthazarneveu 
- [x] add new loss term for noise reconstruction
- [x] handle multiple cost terms

- [x] report receptive field in configuration

# inference script
- [x] add SNR metrics

**Comment by MathildeDupouy** [comment]
> # Training
> @MathildeDupouy
> 
> * [ ]  dataloader fixed and random
> * [ ] manage snr ?
> * [ ] collate
>

**Comment by balthazarneveu** [comment]
Remaining todos =
- [ ] keep a copy of best model
- [ ] Find best & worse examples
- [ ] infer with any voice signal
